// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://othrujztxqktmnwiptao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90aHJ1anp0eHFrdG1ud2lwdGFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc4MzAxODYsImV4cCI6MjEwMzQwNjE4Nn0.uxE88af8rt4IH-Q1ltjkfryhNj-c2ccEzm92U7V3DAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});